# Generated by Django 5.1.6 on 2025-03-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0003_auto_20250303_1258'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masjid',
            table='masjid',
        ),
    ]
