# Generated by Django 5.1.6 on 2025-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0004_alter_masjid_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitas',
            name='tipe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masjid',
            name='fasilitas',
            field=models.ManyToManyField(blank=True, through='mosque.MasjidFasilitas', to='mosque.fasilitas'),
        ),
        migrations.AddField(
            model_name='masjid',
            name='kegiatan',
            field=models.ManyToManyField(blank=True, through='mosque.MasjidKegiatan', to='mosque.kegiatan'),
        ),
    ]
